version: '3.1'

services:

  wordpress:
    image: wordpress:php7.2-apache
    ports:
      - 84:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: imta.uaysen.cl
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: imta.uaysen.cl
      LETSENCRYPT_EMAIL: francisco.salazar.12@sansano.usm.cl
    expose:
      - 80
    links:
      - mysql:mysql

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
